import type { Product } from "./types";

const img = (slug: string, n: number) => `/products/${slug}-${n}.webp`;
const images = (slug: string, name: string) => [1,2,3].map((n) => ({ id: `${slug}-image-${n}`, url: img(slug,n), alt: `${name}, studio view ${n}`, sortOrder:n }));
const variants = (slug:string, baseSku:string, finishes:Array<[string,string]>, configs:string[], price:number, compare:number|null, inventory=18) => finishes.flatMap(([finish,finishHex],fi)=>configs.map((configuration,ci)=>({ id:`${slug}-${fi}-${ci}`, sku:`${baseSku}-${configuration.replace(/\W/g,"").toUpperCase()}-${finish.replace(/\W/g,"").slice(0,3).toUpperCase()}`, finish, finishHex, configuration, price:price+(ci*30_000), compareAtPrice:compare===null?null:compare+(ci*30_000), inventory:Math.max(0,inventory-fi*3-ci*2), imageUrls:[img(slug,1),img(slug,2),img(slug,3)] })));

export const PRODUCTS: Product[] = [
  { id:"prod_arc_one",slug:"cedar-arc-one",name:"CEDAR Arc One",category:"phones",shortDescription:"6.7-inch AMOLED phone with an all-day battery and pro-grade camera.",description:"Arc One balances a bright adaptive display, dependable battery life and a versatile camera system in a precise aluminium body built for everyday use.",rating:4.6,reviewCount:328,specifications:{Display:"6.7-inch AMOLED, 120 Hz",Camera:"50 MP main + 12 MP ultra-wide",Battery:"5,000 mAh, 65 W charging",Connectivity:"5G, Wi-Fi 6, NFC",Protection:"IP68"},deliveryEstimate:"Next-day delivery in Lagos; 2–3 days in Abuja",warranty:"24-month CEDAR warranty",featured:true,newArrival:true,images:images("cedar-arc-one","CEDAR Arc One"),variants:variants("cedar-arc-one","CA1",[["Forest Blue","#234a79"],["Midnight","#15171b"],["Sandalwood","#c8b49a"]],["128GB","256GB","512GB"],599000,649000,20),relatedSlugs:["pulse-buds-pro","volt-65w","meridian-watch-s2"] },
  { id:"prod_arc_air",slug:"cedar-arc-air",name:"CEDAR Arc Air",category:"phones",shortDescription:"A lighter 6.2-inch phone with sharp cameras and fast charging.",description:"Arc Air keeps the essentials fast and comfortable with a compact high-refresh display, balanced cameras and reliable two-day battery life.",rating:4.5,reviewCount:184,specifications:{Display:"6.2-inch OLED, 120 Hz",Camera:"48 MP dual camera",Battery:"4,500 mAh",Connectivity:"5G, Wi-Fi 6",Protection:"IP67"},deliveryEstimate:"1–3 business days",warranty:"24-month CEDAR warranty",featured:false,newArrival:true,images:images("cedar-arc-air","CEDAR Arc Air"),variants:variants("cedar-arc-air","CAA",[["Cobalt","#315d9b"],["Graphite","#33363b"]],["128GB","256GB"],429000,459000,14),relatedSlugs:["pulse-buds-pro","volt-pocket-20k"] },
  { id:"prod_auralite_h3",slug:"auralite-h3",name:"Auralite H3",category:"headphones",shortDescription:"Wireless noise-cancelling headphones tuned for long sessions.",description:"Auralite H3 combines adaptive noise control, spacious sound and soft replaceable cushions for work, travel and focused listening.",rating:4.7,reviewCount:320,specifications:{Drivers:"40 mm bio-cellulose",Battery:"42 hours",Charging:"USB-C fast charge",Wireless:"Bluetooth 5.4",Weight:"248 g"},deliveryEstimate:"Get it tomorrow in Lagos",warranty:"18-month warranty",featured:true,newArrival:false,images:images("auralite-h3","Auralite H3"),variants:variants("auralite-h3","AH3",[["Ink","#17191d"],["Stone","#c8c2b8"]],["Standard"],149000,179000,24),relatedSlugs:["volt-65w","ember-mini"] },
  { id:"prod_pulse_buds",slug:"pulse-buds-pro",name:"Pulse Buds Pro",category:"earbuds",shortDescription:"Compact adaptive-noise-cancelling earbuds with clear calls.",description:"Pulse Buds Pro deliver focused sound, wind-reduced microphones and a pocketable charging case with wireless charging.",rating:4.4,reviewCount:215,specifications:{Battery:"8 + 24 hours with case",Audio:"Adaptive ANC",Protection:"IPX5",Charging:"USB-C and Qi",Wireless:"Bluetooth 5.4"},deliveryEstimate:"Get it tomorrow in Lagos",warranty:"12-month warranty",featured:true,newArrival:true,images:images("pulse-buds-pro","Pulse Buds Pro"),variants:variants("pulse-buds-pro","PBP",[["Cloud","#dedbd3"],["Ink","#1c1d20"],["Sky","#7d9fc6"]],["Standard"],89000,109000,30),relatedSlugs:["cedar-arc-one","volt-pocket-20k"] },
  { id:"prod_meridian_s2",slug:"meridian-watch-s2",name:"Meridian Watch S2",category:"smartwatches",shortDescription:"A bright GPS smartwatch for health, training and daily plans.",description:"Meridian Watch S2 tracks workouts, sleep and recovery with a crisp round display and five-day battery.",rating:4.6,reviewCount:180,specifications:{Display:"1.43-inch AMOLED",Battery:"Up to 5 days",Sensors:"Heart rate, SpO₂, temperature",GPS:"Dual-band",Protection:"5 ATM"},deliveryEstimate:"1–2 business days",warranty:"18-month warranty",featured:true,newArrival:false,images:images("meridian-watch-s2","Meridian Watch S2"),variants:variants("meridian-watch-s2","MWS2",[["Ocean Blue","#244873"],["Black","#1e2022"],["Sand","#c1aa87"]],["42mm","46mm"],129000,149000,16),relatedSlugs:["cedar-arc-one","pulse-buds-pro"] },
  { id:"prod_ember_mini",slug:"ember-mini",name:"Ember Mini",category:"speakers",shortDescription:"Room-filling portable speaker with balanced bass and clear vocals.",description:"Ember Mini is a compact weather-resistant speaker with simple controls, stereo pairing and 16-hour battery life.",rating:4.5,reviewCount:96,specifications:{Output:"30 W",Battery:"16 hours",Protection:"IP67",Wireless:"Bluetooth 5.3",Weight:"680 g"},deliveryEstimate:"1–3 business days",warranty:"12-month warranty",featured:true,newArrival:false,images:images("ember-mini","Ember Mini"),variants:variants("ember-mini","EMB",[["Ink","#202226"],["Cobalt","#315d9b"],["Clay","#b56042"]],["Standard"],69000,89000,26),relatedSlugs:["auralite-h3","pulse-buds-pro"] },
  { id:"prod_framekey",slug:"framekey-k2",name:"FrameKey K2",category:"keyboards",shortDescription:"Low-profile wireless mechanical keyboard for focused work.",description:"FrameKey K2 offers quiet tactile switches, multi-device pairing and a precise aluminium frame for desk setups that work hard.",rating:4.5,reviewCount:142,specifications:{Layout:"75%",Switches:"Quiet tactile",Wireless:"2.4 GHz + Bluetooth",Battery:"Up to 90 days",Compatibility:"Windows, macOS, Android"},deliveryEstimate:"2–4 business days",warranty:"18-month warranty",featured:true,newArrival:true,images:images("framekey-k2","FrameKey K2"),variants:variants("framekey-k2","FK2",[["Graphite","#33363b"],["Silver","#b9bdc3"]],["Tactile","Linear"],119000,null,12),relatedSlugs:["volt-65w","ember-mini"] },
  { id:"prod_luma_c1",slug:"luma-c1",name:"Luma C1",category:"cameras",shortDescription:"Compact interchangeable-lens camera for sharp everyday video and stills.",description:"Luma C1 pairs a 24 MP sensor with reliable autofocus, stabilized 4K video and direct USB-C streaming in a travel-ready body.",rating:4.7,reviewCount:118,specifications:{Sensor:"24 MP APS-C",Video:"4K 60 fps",Stabilization:"5-axis",Autofocus:"425-point phase detect",Mount:"Luma M"},deliveryEstimate:"2–4 business days",warranty:"24-month warranty",featured:true,newArrival:true,images:images("luma-c1","Luma C1"),variants:variants("luma-c1","LC1",[["Black","#17191d"],["Silver","#b9bdc3"]],["Body only","18–50mm kit"],349000,399000,8),relatedSlugs:["framekey-k2","volt-65w"] },
  { id:"prod_volt65",slug:"volt-65w",name:"Volt 65W",category:"power",shortDescription:"Compact three-port GaN charger for phones, tablets and laptops.",description:"Volt 65W intelligently shares power across two USB-C ports and one USB-A port in a compact travel body.",rating:4.7,reviewCount:142,specifications:{Output:"65 W total",Ports:"2× USB-C, 1× USB-A",Technology:"GaN",Protection:"Over-current and thermal",Input:"100–240 V"},deliveryEstimate:"Get it tomorrow in Lagos",warranty:"12-month warranty",featured:true,newArrival:false,images:images("volt-65w","Volt 65W"),variants:variants("volt-65w","V65",[["Ink","#202226"],["Cloud","#e2e0db"]],["UK plug"],39000,49000,48),relatedSlugs:["cedar-arc-one","framekey-k2"] },
  { id:"prod_volt20k",slug:"volt-pocket-20k",name:"Volt Pocket 20K",category:"power",shortDescription:"20,000 mAh power bank with a built-in USB-C cable and clear display.",description:"Volt Pocket 20K provides high-capacity travel power, 45 W fast charging and a built-in cable that stays out of the way.",rating:4.6,reviewCount:87,specifications:{Capacity:"20,000 mAh",Output:"45 W USB-C PD",Ports:"2× USB-C, 1× USB-A",Display:"Battery percentage",Protection:"Airline-safe cells"},deliveryEstimate:"1–3 business days",warranty:"12-month warranty",featured:false,newArrival:true,images:images("volt-pocket-20k","Volt Pocket 20K"),variants:variants("volt-pocket-20k","VP20",[["Ink","#202226"],["Cobalt","#315d9b"]],["20,000mAh"],59000,69000,34),relatedSlugs:["pulse-buds-pro","cedar-arc-air"] }
];

export const COLLECTIONS = [
  { slug:"new-arrivals",name:"New arrivals",description:"The latest phones, audio, wearables and everyday power.",productSlugs:PRODUCTS.filter(p=>p.newArrival).map(p=>p.slug) },
  { slug:"audio",name:"Audio",description:"Headphones, earbuds and speakers for work, travel and home.",productSlugs:PRODUCTS.filter(p=>["headphones","earbuds","speakers"].includes(p.category)).map(p=>p.slug) },
  { slug:"mobile",name:"Mobile",description:"Phones, watches and power built to move together.",productSlugs:PRODUCTS.filter(p=>["phones","smartwatches","power"].includes(p.category)).map(p=>p.slug) },
  { slug:"work-setup",name:"Work setup",description:"Focused tools for a capable desk.",productSlugs:PRODUCTS.filter(p=>["keyboards","headphones","cameras","power"].includes(p.category)).map(p=>p.slug) }
];
