import { PRODUCTS, COLLECTIONS } from "../lib/catalog-data";
import postgres from "postgres";

const url=process.env.DATABASE_URL;if(!url)throw new Error("DATABASE_URL is required.");const sql=postgres(url,{max:1});
for(const p of PRODUCTS){
  await sql`insert into cedar_commerce.products(id,slug,name,category,short_description,description,rating,review_count,specifications,delivery_estimate,warranty,featured,new_arrival,related_slugs) values(${p.id},${p.slug},${p.name},${p.category},${p.shortDescription},${p.description},${p.rating},${p.reviewCount},${sql.json(p.specifications)},${p.deliveryEstimate},${p.warranty},${p.featured},${p.newArrival},${sql.json(p.relatedSlugs)}) on conflict(id) do update set name=excluded.name,category=excluded.category,short_description=excluded.short_description,description=excluded.description,rating=excluded.rating,review_count=excluded.review_count,specifications=excluded.specifications,delivery_estimate=excluded.delivery_estimate,warranty=excluded.warranty,featured=excluded.featured,new_arrival=excluded.new_arrival,related_slugs=excluded.related_slugs,updated_at=now()`;
  for(const i of p.images)await sql`insert into cedar_commerce.product_images(id,product_id,url,alt,sort_order) values(${i.id},${p.id},${i.url},${i.alt},${i.sortOrder}) on conflict(id) do update set url=excluded.url,alt=excluded.alt,sort_order=excluded.sort_order`;
  for(const v of p.variants){await sql`insert into cedar_commerce.product_variants(id,product_id,sku,finish,finish_hex,configuration,price,compare_at_price,image_urls) values(${v.id},${p.id},${v.sku},${v.finish},${v.finishHex},${v.configuration},${v.price},${v.compareAtPrice},${sql.json(v.imageUrls)}) on conflict(id) do update set sku=excluded.sku,finish=excluded.finish,finish_hex=excluded.finish_hex,configuration=excluded.configuration,price=excluded.price,compare_at_price=excluded.compare_at_price,image_urls=excluded.image_urls`;await sql`insert into cedar_commerce.inventory(variant_id,available) values(${v.id},${v.inventory}) on conflict(variant_id) do update set available=excluded.available,updated_at=now()`;}
}
for(const c of COLLECTIONS){const [row]=await sql`insert into cedar_commerce.collections(slug,name,description) values(${c.slug},${c.name},${c.description}) on conflict(slug) do update set name=excluded.name,description=excluded.description returning id`;for(let n=0;n<c.productSlugs.length;n++){const p=PRODUCTS.find(x=>x.slug===c.productSlugs[n])!;await sql`insert into cedar_commerce.collection_products(collection_id,product_id,position) values(${row.id},${p.id},${n}) on conflict do nothing`;}}
await sql`insert into cedar_commerce.promo_codes(code,percent_off,minimum_subtotal,starts_at,expires_at) values('CEDAR10',10,100000,now()-interval '1 day',now()+interval '365 days') on conflict(code) do update set active=true,expires_at=excluded.expires_at`;
await sql`insert into cedar_commerce.operator_state(merchant_id,scenario) values('cedar-commerce','unauthorized-field') on conflict do nothing`;
await sql.end();console.log(`Seeded ${PRODUCTS.length} products.`);
