import { businessEventEvidence } from "../../domain/evidence-sources.js";
import type { EvidenceGraphRecord } from "../../domain/evidence.js";
import { decideVerification } from "../../domain/deterministic-verifier.js";
import { verifyAndConstrainManagedRequest } from "../../domain/managed-verification.js";
import { parseGatewayInput, resolveRegisteredIntegration, signatureHash, verifyGatewaySignature } from "../../domain/gateway-policy.js";
import type { GatewayObservationV1 } from "./gateway-observation.js";
import type { EvidenceHistoryEntry } from "../evidence-history/evidence-history-store.js";
import { SupabaseEvidenceHistoryStore } from "../evidence-history/supabase-evidence-history-store.js";
import { createHmac, randomUUID } from "node:crypto";

interface ApiRequest {method?:string;body?:unknown;headers:Record<string,string|string[]|undefined>}
interface ApiResponse {status(code:number):ApiResponse;setHeader(name:string,value:string):void;json(body:unknown):void;end():void}
interface Config{supabaseUrl:string;serviceRoleKey:string;cedarSecret:string;partnerSecret:string;cedarOrigin?:string;environment:Record<string,string|undefined>}

export default async function handler(req:ApiRequest,res:ApiResponse){
  res.setHeader("Cache-Control","no-store");res.setHeader("Vary","Origin");
  const config=readConfig();if(!config){res.status(503).json({error:"GATEWAY_NOT_CONFIGURED"});return}
  const origin=header(req,"origin");if(origin&&config.cedarOrigin&&origin===config.cedarOrigin)res.setHeader("Access-Control-Allow-Origin",origin);
  if(req.method==="OPTIONS"){if(origin&&config.cedarOrigin&&origin!==config.cedarOrigin){res.status(403).end();return}res.setHeader("Access-Control-Allow-Methods","POST");res.setHeader("Access-Control-Allow-Headers","content-type,x-cedar-timestamp,x-cedar-signature");res.status(204).end();return}
  if(req.method!=="POST"){res.status(405).json({error:"METHOD_NOT_ALLOWED"});return}
  const body=typeof req.body==="string"?req.body:JSON.stringify(req.body??{});const timestamp=header(req,"x-cedar-timestamp"),signature=header(req,"x-cedar-signature");
  if(!verifyGatewaySignature(config.cedarSecret,timestamp,body,signature)){res.status(401).json({error:"INVALID_SIGNATURE"});return}
  let raw:unknown;try{raw=typeof req.body==="string"?JSON.parse(req.body):req.body}catch{res.status(400).json({error:"INVALID_JSON"});return}
  const input=parseGatewayInput(raw);if(!input){res.status(422).json({error:"INVALID_DISPATCH"});return}
  if(input.merchantId!=="cedar-commerce"||input.context.source!=="cedar-backend"||input.context.environment!=="synthetic-demo"){res.status(403).json({error:"UNKNOWN_MERCHANT_CONTEXT"});return}
  if(Math.abs(Date.now()-Date.parse(input.occurredAt))>300_000){res.status(401).json({error:"EXPIRED_EVENT"});return}
  const integration=resolveRegisteredIntegration(input.integrationId,config.environment);const evidenceId=`gateway:${input.merchantId}:${input.idempotencyKey}`;
  try{
    const replay=await reserveReplay(config,signatureHash(signature),input.idempotencyKey);if(replay){res.status(409).json({error:"REPLAYED_REQUEST",evidenceId});return}
    if(!integration){const result=blockedResult(evidenceId,"SHADOW_INTEGRATION",Object.keys(input.fields));await persistDispatch(config,input,result,null);res.status(403).json(result);return}
    if(integration.purpose!==input.purpose){const result=blockedResult(evidenceId,"PURPOSE_MISMATCH",Object.keys(input.fields));await persistDispatch(config,input,result,null);res.status(403).json(result);return}
    const store=new SupabaseEvidenceHistoryStore({projectUrl:config.supabaseUrl,serviceRoleKey:config.serviceRoleKey});const contracts=await store.findPurposeContracts(input.integrationId,input.context.environment,input.occurredAt);const contract=contracts.find(c=>c.contract.purpose===input.purpose&&c.contract.validTriggers.includes(input.eventName));
    if(!contract){const result=blockedResult(evidenceId,input.integrationId==="crm-partner"?"STALE_CONTRACT":"POLICY_UNAVAILABLE",Object.keys(input.fields));await persistDispatch(config,input,result,null);res.status(503).json(result);return}
    const observation:GatewayObservationV1={schemaVersion:"gateway-dispatch.v1",observationId:input.idempotencyKey,merchantId:input.merchantId,integrationId:input.integrationId,purpose:input.purpose,eventName:input.eventName,observedAt:input.occurredAt,environment:input.context.environment,attemptedFields:Object.keys(input.fields)};
    const evidence=makeEvidence(evidenceId,input,contract.contract.contractId,contract.contract.version,contract.contract.fields);
    const prevention=verifyAndConstrainManagedRequest({evidence,semanticPayload:input.fields,observedFields:Object.keys(input.fields),purposeContracts:contracts});
    const partner=await deliver(config,integration,input,evidenceId,prevention.payload);const decision=prevention.outcome==="PREVENTED"?"PREVENTED":"ALLOWED";const result={decision,reasonCode:decision==="PREVENTED"?"SCOPE_DRIFT":"WITHIN_SCOPE",allowedFields:Object.keys(prevention.payload).sort(),blockedFields:[...prevention.removedFields].sort(),partnerDelivered:true,forbiddenFieldDelivered:partner.forbiddenFieldReceived,evidenceId};
    if(partner.forbiddenFieldReceived&&prevention.removedFields.length){throw new Error("PARTNER_RECEIVED_FORBIDDEN_FIELD")}
    const event=businessEventEvidence({id:`business:${input.idempotencyKey}`,type:input.eventName,timestamp:input.occurredAt,orderRefHash:String(input.fields["order.id"]??""),integrationId:input.integrationId});await store.appendBusinessEvent(event);
    const entry:EvidenceHistoryEntry={recordId:evidenceId,observationId:input.idempotencyKey,acceptedAt:new Date().toISOString(),observation,evidence,integrationResolution:{status:"RESOLVED",integrationId:input.integrationId,confidence:"AUTHORITATIVE",bindingIds:[],sourceIds:[`merchant:${input.merchantId}`],reason:"Resolved from the authenticated merchant integration registry."},findings:prevention.findings,decision:decideVerification(prevention.findings),enforcement:prevention.outcome==="PREVENTED"?{action:"CONSTRAIN",outcome:"PREVENTED",removedFields:prevention.removedFields,continuedFields:Object.keys(prevention.payload),receiver:{receivedFields:partner.receivedFields,forbiddenFieldReceived:partner.forbiddenFieldReceived}}:null,outcome:prevention.outcome==="PREVENTED"?"PREVENTED":null};
    await Promise.all([store.append(entry),persistDispatch(config,input,result,prevention.payload)]);res.status(200).json(result);
  }catch(error){console.error("[ThirdSight] Gateway dispatch failed.",error instanceof Error?error.message:"Unknown failure");res.status(502).json({error:"GATEWAY_DISPATCH_FAILED",evidenceId});}
}

function makeEvidence(recordId:string,input:NonNullable<ReturnType<typeof parseGatewayInput>>,contractId:string,contractVersion:string,approved:readonly string[]):EvidenceGraphRecord{return{recordId,observedAt:input.occurredAt,integrationId:input.integrationId,integrationResolution:"RESOLVED",should:{status:"KNOWN",confidence:"AUTHORITATIVE",value:{contractId,contractVersion,purpose:input.purpose,fields:approved,operations:["deliver"],validTriggers:[input.eventName]},provenance:[{source:"purpose-contract",sourceId:`${contractId}:${contractVersion}`,observedAt:input.occurredAt,confidence:"AUTHORITATIVE"}]},could:{status:"UNKNOWN",confidence:"UNKNOWN",value:null,provenance:[],reason:"The managed gateway does not infer broader partner capability from a single dispatch."},did:{status:"KNOWN",confidence:"OBSERVED",value:{boundary:"gateway",phase:"ATTEMPTED",pageOrigin:null,destinationOrigin:"partner-lab",destinationPath:`/ingest/${input.integrationId}`,method:"POST",resourceType:"IntegrationEvent",initiatorType:"cedar-backend",hasPostData:true,originRelationship:"CROSS_ORIGIN",dataCategories:Object.keys(input.fields)},provenance:[{source:"gateway",sourceId:input.idempotencyKey,observedAt:input.occurredAt,confidence:"OBSERVED"}]},why:{status:"KNOWN",confidence:"AUTHORITATIVE",value:{eventId:`business:${input.idempotencyKey}`,eventType:input.eventName,correlationStrength:"EXACT_REFERENCE"},provenance:[{source:"business-event",sourceId:`business:${input.idempotencyKey}`,observedAt:input.occurredAt,confidence:"AUTHORITATIVE"}]},coverage:{label:"MULTI_BOUNDARY",boundaries:["gateway"],limitations:["Partner receipt is proven independently by the signed Partner Lab acknowledgement."]}}}
async function deliver(config:Config,integration:NonNullable<ReturnType<typeof resolveRegisteredIntegration>>,input:NonNullable<ReturnType<typeof parseGatewayInput>>,evidenceId:string,fields:Record<string,unknown>){if(!integration.url)throw new Error("PARTNER_URL_NOT_CONFIGURED");const target=new URL(integration.url);if(target.pathname==="/")target.pathname=`/ingest/${integration.receiver}`;const requestId=randomUUID(),timestamp=String(Date.now()),body=JSON.stringify({merchantId:input.merchantId,integrationId:input.integrationId,eventName:input.eventName,fields,context:input.context,evidenceId}),sig=createHmac("sha256",config.partnerSecret).update(`${timestamp}.${requestId}.${body}`).digest("hex");const response=await fetch(target,{method:"POST",headers:{"content-type":"application/json","x-thirdsight-timestamp":timestamp,"x-thirdsight-request-id":requestId,"x-thirdsight-signature":sig},body,cache:"no-store"});const json=await response.json() as{receivedFields?:unknown;forbiddenFieldReceived?:unknown};if(!response.ok||!Array.isArray(json.receivedFields)||typeof json.forbiddenFieldReceived!=="boolean")throw new Error(`PARTNER_DELIVERY_FAILED_${response.status}`);return{receivedFields:json.receivedFields as string[],forbiddenFieldReceived:json.forbiddenFieldReceived}}
function blockedResult(evidenceId:string,reasonCode:string,blockedFields:string[]){return{decision:"PREVENTED",reasonCode,allowedFields:[],blockedFields:[...blockedFields].sort(),partnerDelivered:false,forbiddenFieldDelivered:false,evidenceId}}
async function reserveReplay(c:Config,hash:string,idempotencyKey:string){const existing=await rest(c,`gateway_dispatches?select=evidence_id&idempotency_key=eq.${encodeURIComponent(idempotencyKey)}&limit=1`,{method:"GET"});if((await existing.json() as unknown[]).length)return true;const response=await rest(c,"gateway_replay_nonces",{method:"POST",headers:{"content-type":"application/json","prefer":"return=minimal"},body:JSON.stringify({signature_hash:hash,expires_at:new Date(Date.now()+600_000).toISOString()})},true);return response.status===409}
async function persistDispatch(c:Config,input:NonNullable<ReturnType<typeof parseGatewayInput>>,result:any,forwarded:Record<string,unknown>|null){await rest(c,"gateway_dispatches?on_conflict=evidence_id",{method:"POST",headers:{"content-type":"application/json","prefer":"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({evidence_id:result.evidenceId,merchant_id:input.merchantId,integration_id:input.integrationId,purpose:input.purpose,event_name:input.eventName,idempotency_key:input.idempotencyKey,occurred_at:input.occurredAt,attempted_payload:input.fields,forwarded_payload:forwarded,blocked_fields:result.blockedFields,decision:result.decision,reason_code:result.reasonCode,partner_delivered:result.partnerDelivered,forbidden_field_delivered:result.forbiddenFieldDelivered})})}
async function rest(c:Config,path:string,init:RequestInit,allowConflict=false){const response=await fetch(new URL(`/rest/v1/${path}`,`${c.supabaseUrl}/`),{...init,headers:{...init.headers,apikey:c.serviceRoleKey,authorization:`Bearer ${c.serviceRoleKey}`,accept:"application/json"},cache:"no-store"});if(!response.ok&&!(allowConflict&&response.status===409))throw new Error(`SUPABASE_${response.status}`);return response}
function header(req:ApiRequest,name:string){const value=req.headers[name]??req.headers[name.toLowerCase()];return Array.isArray(value)?value[0]??"":value??""}
function readConfig():Config|null{const p=(globalThis as any).process?.env as Record<string,string|undefined>|undefined;if(!p)return null;const supabaseUrl=p.THIRDSIGHT_SUPABASE_URL?.trim(),serviceRoleKey=p.THIRDSIGHT_SUPABASE_SERVICE_ROLE_KEY?.trim(),cedarSecret=p.CEDAR_INTEGRATION_SECRET?.trim(),partnerSecret=p.PARTNER_GATEWAY_SECRET?.trim();if(!supabaseUrl||!serviceRoleKey||!cedarSecret||!partnerSecret)return null;return{supabaseUrl,serviceRoleKey,cedarSecret,partnerSecret,cedarOrigin:p.CEDAR_COMMERCE_URL?.trim(),environment:p}}
